<?php $title='Cases Reais'; $description='Cases reais da VITRINE IA PRO: TV Sumaré e Conheça Sumaré como aplicações práticas das soluções do ecossistema.'; require __DIR__.'/includes/header.php'; ?>
<section class="section"><span class="eyebrow dark">Cases reais</span><h1>Projetos em operação que ajudam a validar e evoluir nossas soluções.</h1><p class="lead">Os cases mostram aplicação prática. Não são produtos separados: cada um representa uma implantação ou piloto associado a uma solução comercial da VITRINE IA PRO.</p></section>

<section class="section alt"><div class="proof"><div><span class="eyebrow dark">TV Digital + Portal News</span><h2>TV Sumaré</h2><p>A operação da TV Sumaré contribui para validar fluxos de publicação, organização de notícias, gestão de vídeos, distribuição de conteúdo e rotinas editoriais utilizadas na evolução da TV Digital Enterprise e do Portal News AI Pro.</p><div class="securityList"><span>Gestão de notícias e editorias</span><span>Publicação e organização de vídeos</span><span>Integração com fontes de conteúdo</span><span>Painel editorial centralizado</span><span>Rotina multimídia</span><span>Evolução de módulos</span></div><div class="actions"><a class="btn" href="/tv-digital.php">Ver TV Digital Enterprise</a><a class="btn ghost" href="/news.php">Ver Portal News AI Pro</a></div></div><div class="proofBox"><strong>TV Sumaré</strong><span>case real • notícias • vídeos • operação editorial</span></div></div></section>

<section class="section"><div class="proof"><div><span class="eyebrow dark">Guia Digital da Cidade®</span><h2>Conheça Sumaré</h2><p>Conheça Sumaré é o piloto real da vertical de Guia Digital da Cidade®. A aplicação foi estruturada para experiência mobile, atrativos, eventos, hospedagem, gastronomia, mapa e administração de conteúdo.</p><div class="securityList"><span>Atrativos e experiências locais</span><span>Eventos</span><span>Hospedagem e gastronomia</span><span>Mapa e exploração</span><span>Experiência mobile</span><span>Área administrativa</span></div><div class="actions"><a class="btn" href="/guia-digital.php">Ver Guia Digital da Cidade®</a><a class="btn ghost" href="/solicitacao-institucional.php">Levar para minha cidade</a></div></div><div class="proofBox"><strong>Conheça Sumaré</strong><span>piloto real • turismo • cidade • guia digital</span></div></div></section>

<section class="section alt"><span class="eyebrow dark">Como usar estes cases</span><h2>Prova de aplicação, não promessa automática de resultado.</h2><p class="lead">Cada nova implantação depende de contexto, conteúdo, operação, integrações e escopo contratual próprios. Os cases demonstram capacidade técnica e aprendizado operacional aplicado à evolução dos produtos.</p></section>

<section class="section cta"><h2>Quer uma solução semelhante para sua operação?</h2><p class="lead">Receba um diagnóstico para identificar o produto, os módulos e a implantação mais adequados ao seu cenário.</p><div class="actions" style="justify-content:center"><a class="btn" href="/diagnostico.php">Receber diagnóstico</a><a class="btn ghost" href="/solicitacao-institucional.php">Solicitar proposta</a></div></section>
<?php require __DIR__.'/includes/footer.php'; ?>