<?php $title='Cenários de Aplicação'; require __DIR__.'/includes/header.php'; ?>
<section class="section demosIntro appCases">
  <span class="eyebrow dark">Cenários de aplicação</span>
  <h1>Experiências de referência para diferentes decisões de compra.</h1>
  <p class="lead">Antes de solicitar uma proposta, o cliente precisa visualizar como a plataforma se comporta no seu contexto. Por isso, cada cenário tem narrativa, prioridades e operação próprias: governo municipal, legislativo, mídia regional e TV Digital.</p>
  <div class="demoTiles focused"><a href="/demos/cidade-inteligente-360/" class="tile city featured"><strong>Cidade Inteligente 360</strong><span>Aplicação integrada para gestores que desejam visualizar comunicação pública, mídia e TV Digital funcionando juntas.</span></a><a href="/demos/municipio-360/" class="tile gov"><strong>Município 360</strong><span>Foco em serviços, informações oficiais, prestação de contas e relacionamento com o cidadão.</span></a><a href="/demos/camara-360/" class="tile chamber"><strong>Câmara 360</strong><span>Foco em sessões, proposições, vereadores, transparência legislativa e TV Câmara.</span></a><a href="/demos/news-360/" class="tile news"><strong>News 360</strong><span>Foco em audiência, manchetes, editorias, conteúdo regional e monetização.</span></a><a href="/demos/tv-360/" class="tile tv"><strong>TV 360</strong><span>Foco em transmissão ao vivo, programação, entrevistas, podcasts e acervo.</span></a></div>
</section>
<section class="section alt"><span class="eyebrow dark">Uso comercial</span><h2>Os cenários não são produtos separados. São caminhos de decisão.</h2><p class="lead">A Vitrine AI Pro é licenciada e configurada conforme o perfil da operação. Os cenários servem para orientar a conversa comercial, demonstrar possibilidades e acelerar a definição do escopo antes da proposta.</p><div class="actions"><a class="btn" href="/diagnostico.php">Receber diagnóstico</a><a class="btn ghost" href="/solicitacao-institucional.php">Solicitar apresentação</a></div></section>
<?php require __DIR__.'/includes/footer.php'; ?>
