<?php $title='Diagnóstico Estratégico'; require __DIR__.'/includes/header.php'; ?>
<section class="section"><span class="eyebrow dark">Diagnóstico estratégico</span><h1>Encontre a solução mais adequada antes da proposta.</h1><p class="lead">O diagnóstico identifica se sua necessidade é atendida por um produto do ecossistema VITRINE IA PRO ou se exige desenvolvimento sob medida. Ao final, você recebe um caminho comercial recomendado.</p>
<form class="formGrid" method="post" action="/diagnostico-resultado.php"><?= csrf_field() ?>
<label>Perfil da organização<select name="perfil" required><option value="">Selecione</option><option>Prefeitura ou Secretaria</option><option>Câmara Municipal</option><option>Autarquia / Fundação / Consórcio</option><option>Portal de Notícias / Rádio / Jornal</option><option>TV Web / Projeto Audiovisual</option><option>Empresa / Comércio / Prestador de Serviços</option><option>Operador de Turismo / Cidade</option><option>Marca / Profissional / Equipe de Comunicação</option><option>Instituição de Ensino / Projeto Educacional</option><option>Outro</option></select></label>
<label>Cidade/Estado<input name="cidade" placeholder="Ex: Sumaré/SP"></label>
<label>Principal necessidade<select name="necessidade_tipo" required><option value="">Selecione</option><option>TV Digital / vídeos / transmissões</option><option>Portal de notícias / mídia regional</option><option>Turismo / guia digital da cidade</option><option>Redes sociais / produção de conteúdo</option><option>Governo digital / comunicação pública</option><option>Sistema ou plataforma sob medida</option><option>Cursos / capacitação digital</option><option>Saúde digital</option><option>Ainda não sei</option></select></label>
<label>Situação atual<select name="portal"><option>Já possui estrutura, mas precisa modernizar</option><option>Possui apenas site ou canais simples</option><option>Usa principalmente redes sociais</option><option>Precisa implantar uma operação completa</option></select></label>
<label class="full">Principal resultado esperado<textarea name="objetivo" required placeholder="Descreva o que você quer melhorar, criar, automatizar ou vender."></textarea></label>
<button class="btn">Gerar recomendação</button><a class="btn ghost" href="/solicitacao-institucional.php">Ir direto para proposta</a></form></section>
<section class="section alt"><h2>O diagnóstico qualifica a oportunidade comercial.</h2><div class="grid three"><article class="problem"><h3>1. Necessidade</h3><p>Identifica o problema principal e o perfil da operação.</p></article><article class="problem"><h3>2. Solução</h3><p>Relaciona a necessidade a um produto real ou desenvolvimento sob medida.</p></article><article class="problem"><h3>3. Próxima ação</h3><p>Conduz para a página correta, demonstração ou solicitação de proposta.</p></article></div></section>
<?php require __DIR__.'/includes/footer.php'; ?>
