<?php
$title='Diagnóstico Estratégico';
$perfilPrefill=trim((string)($_GET['perfil'] ?? ''));
$necessidadePrefill=trim((string)($_GET['necessidade_tipo'] ?? ''));
$segmento=trim((string)($_GET['segmento'] ?? ''));
$origem=trim((string)($_GET['origem'] ?? ''));
function selected_opt(string $value,string $current): string { return $value===$current?' selected':''; }
require __DIR__.'/includes/header.php';
?>
<section class="section diagnosisHero"><span class="eyebrow dark">Diagnóstico estratégico</span><h1>Conte o que você precisa. Nós identificamos o melhor caminho digital.</h1><p class="lead">O diagnóstico identifica se sua necessidade é atendida por uma solução SaaS da VITRINE IA PRO, por uma base personalizada, por um modelo White Label ou por desenvolvimento sob medida.</p>
<form class="formGrid" method="post" action="/diagnostico-resultado.php"><?= csrf_field() ?>
<input type="hidden" name="segmento" value="<?= e($segmento) ?>"><input type="hidden" name="origem" value="<?= e($origem) ?>">
<label>Perfil da organização<select name="perfil" required><option value="">Selecione</option><option<?=selected_opt('Prefeitura ou Secretaria',$perfilPrefill)?>>Prefeitura ou Secretaria</option><option<?=selected_opt('Câmara Municipal',$perfilPrefill)?>>Câmara Municipal</option><option<?=selected_opt('Autarquia / Fundação / Consórcio',$perfilPrefill)?>>Autarquia / Fundação / Consórcio</option><option<?=selected_opt('Portal de Notícias / Rádio / Jornal',$perfilPrefill)?>>Portal de Notícias / Rádio / Jornal</option><option<?=selected_opt('TV Web / Projeto Audiovisual',$perfilPrefill)?>>TV Web / Projeto Audiovisual</option><option<?=selected_opt('Empresa / Comércio / Prestador de Serviços',$perfilPrefill)?>>Empresa / Comércio / Prestador de Serviços</option><option<?=selected_opt('Imobiliária / Corretor',$perfilPrefill)?>>Imobiliária / Corretor</option><option<?=selected_opt('ONG / Associação / Terceiro Setor',$perfilPrefill)?>>ONG / Associação / Terceiro Setor</option><option<?=selected_opt('Operador de Turismo / Cidade',$perfilPrefill)?>>Operador de Turismo / Cidade</option><option<?=selected_opt('Marca / Profissional / Equipe de Comunicação',$perfilPrefill)?>>Marca / Profissional / Equipe de Comunicação</option><option<?=selected_opt('Instituição de Ensino / Projeto Educacional',$perfilPrefill)?>>Instituição de Ensino / Projeto Educacional</option><option>Outro</option></select></label>
<label>Cidade/Estado<input name="cidade" placeholder="Ex: Sumaré/SP"></label>
<label>Principal necessidade<select name="necessidade_tipo" required><option value="">Selecione</option><option<?=selected_opt('TV Digital / vídeos / transmissões',$necessidadePrefill)?>>TV Digital / vídeos / transmissões</option><option<?=selected_opt('Portal de notícias / mídia regional',$necessidadePrefill)?>>Portal de notícias / mídia regional</option><option<?=selected_opt('Turismo / guia digital da cidade',$necessidadePrefill)?>>Turismo / guia digital da cidade</option><option<?=selected_opt('Redes sociais / produção de conteúdo',$necessidadePrefill)?>>Redes sociais / produção de conteúdo</option><option<?=selected_opt('Governo digital / comunicação pública',$necessidadePrefill)?>>Governo digital / comunicação pública</option><option<?=selected_opt('CRM / vendas / atendimento',$necessidadePrefill)?>>CRM / vendas / atendimento</option><option<?=selected_opt('Site / portal / aplicativo',$necessidadePrefill)?>>Site / portal / aplicativo</option><option<?=selected_opt('Integrações / automações / IA',$necessidadePrefill)?>>Integrações / automações / IA</option><option<?=selected_opt('Sistema ou plataforma sob medida',$necessidadePrefill)?>>Sistema ou plataforma sob medida</option><option<?=selected_opt('Cursos / capacitação digital',$necessidadePrefill)?>>Cursos / capacitação digital</option><option<?=selected_opt('Saúde digital',$necessidadePrefill)?>>Saúde digital</option><option<?=selected_opt('Ainda não sei',$necessidadePrefill)?>>Ainda não sei</option></select></label>
<label>Modelo desejado<select name="modelo_comercial"><option>Ainda não sei</option><option>SaaS</option><option>SaaS personalizado</option><option>White Label</option><option>Projeto sob medida</option></select></label>
<label>Situação atual<select name="portal"><option>Já possui estrutura, mas precisa modernizar</option><option>Possui apenas site ou canais simples</option><option>Usa principalmente redes sociais</option><option>Precisa implantar uma operação completa</option></select></label>
<label class="full">Principal resultado esperado<textarea name="objetivo" required placeholder="Descreva o que você quer criar, melhorar, automatizar, integrar, vender ou escalar."></textarea></label>
<button class="btn">Gerar recomendação</button><a class="btn ghost" href="/solicitacao-institucional.php">Ir direto para proposta</a></form></section>
<section class="section alt"><h2>O diagnóstico começa pelo problema, não pelo produto.</h2><div class="grid three"><article class="problem"><h3>1. Necessidade</h3><p>Entendemos o desafio, o perfil da operação e o resultado esperado.</p></article><article class="problem"><h3>2. Modelo</h3><p>Avaliamos se o melhor caminho é SaaS, personalização, White Label ou desenvolvimento específico.</p></article><article class="problem"><h3>3. Próxima ação</h3><p>Conduzimos para solução existente, demonstração, escopo técnico ou proposta comercial.</p></article></div></section>
<?php require __DIR__.'/includes/footer.php'; ?>
