<?php $title='Governo Digital IA'; $description='Governo Digital IA da VITRINE IA PRO: portal institucional, notícias, documentos, agenda, atendimento digital, IA de apoio e relatórios para órgãos públicos.'; require __DIR__.'/includes/header.php'; ?>
<section class="hero govHero2 refinedHero"><div class="heroGrid"><div><span class="eyebrow">Governo Digital IA</span><h1>Organize informação pública, atendimento e comunicação em uma operação digital própria.</h1><p>O Governo Digital IA reúne portal institucional, páginas oficiais, notícias, documentos, agenda, solicitações e recursos de atendimento em uma estrutura preparada para implantação consultiva em prefeituras, câmaras, autarquias e entidades públicas.</p><div class="actions"><a class="btn" href="/solicitacao-institucional.php">Solicitar apresentação</a><a class="btn ghost" href="/contratacao-publica.php">Contratação pública</a></div><div class="heroTrust"><span>Comunicação oficial</span><span>Transparência</span><span>Atendimento digital</span><span>Documentos públicos</span></div></div><div class="panel govDash refinedPanel"><h3>Operação institucional</h3><div class="miniStats"><span>Portal</span><span>Serviços</span><span>Agenda</span><span>Relatórios</span></div></div></div></section>

<section class="section"><span class="eyebrow dark">Para quem é</span><h2>Estrutura digital para diferentes perfis de órgão público.</h2><p class="lead">A implantação é configurada conforme o tipo de instituição, a maturidade digital e os processos que precisam ser organizados.</p><div class="grid three"><article class="card govAccent"><h3>Prefeituras e secretarias</h3><p>Notícias oficiais, agenda, documentos, serviços, solicitações e comunicação com a população.</p></article><article class="card govAccent"><h3>Câmaras municipais</h3><p>Comunicação legislativa, sessões, transparência, páginas institucionais, documentos e conteúdo público.</p></article><article class="card govAccent"><h3>Autarquias, fundações e consórcios</h3><p>Informação institucional, documentos, orientações, atendimento digital e prestação de contas.</p></article></div></section>

<section class="section alt"><span class="eyebrow dark">Módulos disponíveis</span><h2>Uma base institucional que pode evoluir por escopo.</h2><div class="pillGrid"><span>Portal Institucional</span><span>Páginas Oficiais</span><span>Notícias Institucionais</span><span>Solicitações / Atendimento</span><span>Diagnóstico Digital</span><span>Documentos Públicos</span><span>Agenda Institucional</span><span>IA de Atendimento</span><span>Relatórios de Atendimento</span><span>Landing Institucional</span></div><p class="note" style="margin-top:18px">Integrações com sistemas oficiais, bases de dados ou serviços externos dependem de disponibilidade técnica, autorização e escopo específico. Recursos como IPTU, alvarás ou tributos só são incluídos quando houver integração formal com o sistema responsável.</p></section>

<section class="section"><span class="eyebrow dark">Modelo de contratação</span><h2>Venda consultiva, escopo definido e documentação de apoio.</h2><p class="lead">O processo começa pelo diagnóstico institucional. A proposta final define módulos, implantação, integrações, treinamento, suporte e requisitos de contratação.</p><div class="grid three"><article class="card"><h3>Diagnóstico</h3><p>Mapeamento da necessidade, canais atuais, processos, integrações e prioridades do órgão.</p></article><article class="card govAccent"><h3>Governo</h3><h2>Referência: R$ 2.500/mês</h2><p>Licenciamento para operação institucional com módulos definidos conforme o escopo e a implantação.</p></article><article class="card"><h3>Enterprise</h3><h2>Referência: R$ 4.500/mês</h2><p>Para estruturas mais amplas, múltiplas áreas, integrações e requisitos adicionais de operação e suporte.</p></article></div><p class="note" style="margin-top:18px">Valores são referências do catálogo. A contratação pública depende de proposta formal, escopo, documentação e análise do órgão.</p></section>

<section class="section alt"><div class="split"><div><span class="eyebrow dark">Demonstrações por contexto</span><h2>Visualize antes de definir o projeto.</h2><p class="lead">Município 360 apresenta um cenário de prefeitura e secretarias. Câmara 360 apresenta um cenário legislativo. Cidade Inteligente 360 demonstra uma visão integrada de comunicação e serviços digitais.</p><div class="actions"><a class="btn" href="/demos/municipio-360/">Município 360</a><a class="btn ghost" href="/demos/camara-360/">Câmara 360</a></div></div><div class="card govAccent"><h3>Demonstração não é promessa de integração</h3><p>Os cenários 360 ajudam a visualizar possibilidades. A proposta contratual sempre identifica quais módulos, dados e integrações serão efetivamente entregues.</p><a class="btn small" href="/demonstracoes.php">Ver demonstrações</a></div></div></section>

<section class="section publicFlow"><span class="eyebrow dark">Caminho institucional</span><h2>Da necessidade à análise do órgão.</h2><div class="flowSteps"><span>Necessidade</span><span>Diagnóstico</span><span>Escopo</span><span>Proposta</span><span>Documentação</span><span>Análise do órgão</span></div><div class="actions" style="justify-content:center;margin-top:28px"><a class="btn" href="/contratacao-publica.php">Entender contratação pública</a><a class="btn ghost" href="/documentos-publicos.php">Ver documentos</a></div></section>

<section class="section cta"><h2>Solicite uma apresentação para seu órgão.</h2><p class="lead">Receba uma proposta direcionada ao perfil da instituição, com escopo, módulos, documentação de apoio e próximos passos.</p><div class="actions" style="justify-content:center"><a class="btn" href="/solicitacao-institucional.php">Solicitar apresentação</a><a class="btn ghost" href="/diagnostico.php">Receber diagnóstico</a></div></section>
<?php require __DIR__.'/includes/footer.php'; ?>