<?php
require __DIR__ . '/vendor/autoload.php';
$app = require __DIR__ . '/bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
function cols($t){ return Schema::hasTable($t) ? Schema::getColumnListing($t) : []; }
function keep($cols,$data){ $o=[]; foreach($data as $k=>$v){ if(in_array($k,$cols,true)) $o[$k]=$v; } if(in_array('created_at',$cols,true)) $o['created_at']=now(); if(in_array('updated_at',$cols,true)) $o['updated_at']=now(); return $o; }
function col($cols,$names,$fallback=null){ foreach($names as $n){ if(in_array($n,$cols,true)) return $n; } return $fallback; }
function upsert_named($table,$nameCols,$data){ if(!Schema::hasTable($table)){ echo "Tabela {$table} não existe.\n"; return null; } $cols=cols($table); $ncol=col($cols,$nameCols); if(!$ncol){ echo "Tabela {$table} sem coluna de nome conhecida.\n"; return null; } $label=$data[$ncol] ?? $data['name'] ?? $data['nome'] ?? $data['title'] ?? $data['titulo'] ?? null; if(!$label){ echo "Registro sem nome para {$table}.\n"; return null; } $row=DB::table($table)->where($ncol,$label)->first(); $payload=keep($cols,$data); if($row){ DB::table($table)->where('id',$row->id)->update($payload); echo "Atualizado: {$table} / {$label}\n"; return (int)$row->id; } $id=DB::table($table)->insertGetId($payload); echo "Criado: {$table} / {$label}\n"; return (int)$id; }
function provider_id($name){ if(!Schema::hasTable('ai_providers')) return null; $cols=cols('ai_providers'); foreach(['name','nome','title','titulo'] as $c){ if(in_array($c,$cols,true)){ $r=DB::table('ai_providers')->where($c,$name)->first(); return $r ? (int)$r->id : null; } } return null; }
$pcols=cols('ai_providers'); $pName=col($pcols,['name','nome','title','titulo'],'name');
foreach([['OpenAI','openai','Atendimento, comercial e tarefas gerais.'],['Gemini','gemini','Conteúdo, análise e editorial.'],['HeyGen','heygin','Vídeos, avatar e Repórter IA.'],['Manual / Interno','manual','Execução manual ou interna.']] as $p){ upsert_named('ai_providers',['name','nome','title','titulo'],[$pName=>$p[0],'description'=>$p[2],'descricao'=>$p[2],'type'=>$p[1],'tipo'=>$p[1],'provider'=>$p[1],'provedor'=>$p[1],'status'=>'Ativo','is_active'=>1,'ativo'=>1]); }
$acols=cols('ai_agents'); $aName=col($acols,['name','nome','title','titulo'],'name'); $providerFk=col($acols,['ai_provider_id','provider_id','provedor_id']);
$agents=[['Agente Comercial','Qualifica leads, recomenda produtos, gera resumo comercial e próximo passo.','OpenAI'],['Agente Marketing','Cria campanhas, calendários, textos e orientações de divulgação.','Gemini'],['Agente Editorial News','Apoia pauta, revisão, expansão editorial e organização de notícias.','Gemini'],['Agente Suporte','Classifica chamados, sugere resposta e encaminha prioridade.','OpenAI'],['Agente Diagnóstico Cliente','Analisa necessidade do cliente e recomenda solução do ecossistema.','OpenAI'],['Agente Conteúdo Institucional','Gera textos institucionais, páginas e materiais de apresentação.','Gemini'],['Agente Operacional Master','Acompanha implantação, licenças, módulos, filas e pendências.','Manual / Interno']];
$ids=[]; foreach($agents as $a){ $data=[$aName=>$a[0],'description'=>$a[1],'descricao'=>$a[1],'prompt'=>$a[1],'system_prompt'=>$a[1],'status'=>'Ativo','is_active'=>1,'ativo'=>1]; if($providerFk && ($pid=provider_id($a[2]))) $data[$providerFk]=$pid; $ids[$a[0]]=upsert_named('ai_agents',['name','nome','title','titulo'],$data); }
if(Schema::hasTable('ai_queues')){ $c=cols('ai_queues'); $n=col($c,['name','nome','title','titulo','task','tarefa'],'title'); $fk=col($c,['ai_agent_id','agent_id','agente_id']); $d=[$n=>'Fila inicial - Diagnóstico comercial','description'=>'Fila operacional inicial para testar o Agente Comercial.','descricao'=>'Fila operacional inicial para testar o Agente Comercial.','status'=>'Pendente','priority'=>'Média','prioridade'=>'Média','payload'=>json_encode(['origem'=>'seed_master_1_4_1'],JSON_UNESCAPED_UNICODE)]; if($fk && !empty($ids['Agente Comercial'])) $d[$fk]=$ids['Agente Comercial']; upsert_named('ai_queues',['name','nome','title','titulo','task','tarefa'],$d); }
if(Schema::hasTable('ai_alerts')){ $c=cols('ai_alerts'); $n=col($c,['title','titulo','name','nome'],'title'); upsert_named('ai_alerts',['title','titulo','name','nome'],[$n=>'Centro IA em homologação operacional','message'=>'Dados-base criados. Próximo teste: executar Agente Comercial IA.','mensagem'=>'Dados-base criados. Próximo teste: executar Agente Comercial IA.','description'=>'Alerta inicial de homologação.','descricao'=>'Alerta inicial de homologação.','status'=>'Aberto','level'=>'Info','nivel'=>'Info']); }
if(Schema::hasTable('ai_memories')){ $c=cols('ai_memories'); $n=col($c,['title','titulo','name','nome','key','chave'],'title'); upsert_named('ai_memories',['title','titulo','name','nome','key','chave'],[$n=>'Contexto operacional Vitrine AI Pro','content'=>'Ecossistema com Centro Operacional Master, produtos SaaS, agentes IA e foco em vendas, implantação e suporte.','conteudo'=>'Ecossistema com Centro Operacional Master, produtos SaaS, agentes IA e foco em vendas, implantação e suporte.','value'=>'Centro IA operacional inicial.','valor'=>'Centro IA operacional inicial.','status'=>'Ativo']); }
if(Schema::hasTable('ai_executions')){ $c=cols('ai_executions'); $n=col($c,['title','titulo','name','nome','task','tarefa'],'title'); $fk=col($c,['ai_agent_id','agent_id','agente_id']); $d=[$n=>'Execução inicial - Homologação Centro IA','input'=>'Teste inicial de estrutura operacional.','entrada'=>'Teste inicial de estrutura operacional.','output'=>'Centro IA preparado com provedores e agentes-base.','saida'=>'Centro IA preparado com provedores e agentes-base.','status'=>'Concluído','started_at'=>now(),'finished_at'=>now()]; if($fk && !empty($ids['Agente Operacional Master'])) $d[$fk]=$ids['Agente Operacional Master']; upsert_named('ai_executions',['title','titulo','name','nome','task','tarefa'],$d); }
if(Schema::hasTable('ai_consumptions')){ $c=cols('ai_consumptions'); $n=col($c,['title','titulo','name','nome','description','descricao'],'title'); upsert_named('ai_consumptions',['title','titulo','name','nome','description','descricao'],[$n=>'Consumo inicial - seed operacional','provider'=>'Manual / Interno','provedor'=>'Manual / Interno','tokens'=>0,'cost'=>0,'custo'=>0,'status'=>'Registrado']); }
$labels=['AiQueueResource.php'=>['Filas de IA','Fila de IA','Filas de IA'],'AiConsumptionResource.php'=>['Consumo de IA','Consumo de IA','Consumo de IA'],'AiAlertResource.php'=>['Alertas de IA','Alerta de IA','Alertas de IA'],'AiMemoryResource.php'=>['Memória da IA','Memória da IA','Memória da IA'],'AiExecutionResource.php'=>['Execuções de IA','Execução de IA','Execuções de IA'],'AiAgentResource.php'=>['Agentes IA','Agente IA','Agentes IA'],'AiProviderResource.php'=>['Provedores IA','Provedor IA','Provedores IA']];
foreach($labels as $file=>$vals){ $path=__DIR__.'/app/Filament/Resources/'.$file; if(!file_exists($path)) continue; $s=file_get_contents($path); foreach(['navigationLabel'=>$vals[0],'modelLabel'=>$vals[1],'pluralModelLabel'=>$vals[2]] as $prop=>$value){ $line="protected static ?string \${$prop} = '{$value}';"; $pattern='/protected\s+static\s+\?string\s+\$'.preg_quote($prop,'/').'\s*=\s*[\'\"][^\'\"]*[\'\"]\s*;/'; if(preg_match($pattern,$s)) $s=preg_replace($pattern,$line,$s); else $s=preg_replace('/class\s+([A-Za-z0-9_]+)\s+extends\s+Resource\s*\{/','class $1 extends Resource' . "\n{\n    {$line}",$s,1); } file_put_contents($path,$s); echo "Labels atualizados: {$file}\n"; }
echo "\nMASTER 1.4.1 Centro IA Operacional Seed aplicado.\n";
echo "Agora rode cache: php artisan optimize:clear && php artisan filament:cache-components && php artisan config:cache && php artisan route:cache\n";
