<?php $title='Portal News AI Pro'; $description='Portal News AI Pro da VITRINE IA PRO: portal de notícias com RSS, IA editorial, editorias, monetização, newsletter e operação profissional para veículos regionais.'; require __DIR__.'/includes/header.php'; ?>
<section class="mediaHero refinedHero"><div><span class="eyebrow">Portal News AI Pro</span><h1>Transforme seu portal em uma operação editorial e comercial mais eficiente.</h1><p>O Portal News AI Pro reúne publicação de notícias, captura de conteúdo, organização por editorias, apoio de IA e recursos de monetização para veículos que precisam crescer audiência sem aumentar a complexidade da operação.</p><div class="actions"><a class="btn" href="/solicitacao-institucional.php">Solicitar proposta</a><a class="btn ghost darkGhost" href="/casos-reais.php">Ver aplicação real</a></div><div class="heroTrust"><span>Notícias e editorias</span><span>RSS e captura</span><span>IA editorial</span><span>Monetização</span></div></div><div class="mediaPanel"><strong>Portal News AI Pro</strong><span>Conteúdo diário</span><span>RSS e fontes</span><span>IA de apoio</span><span>Banners e newsletter</span></div></section>

<section class="section"><span class="eyebrow dark">Operação editorial</span><h2>Publique mais, organize melhor e crie novas oportunidades comerciais.</h2><p class="lead">A plataforma foi desenhada para portais, rádios, jornais, TVs Web e projetos de mídia regional que precisam centralizar conteúdo e reduzir tarefas manuais.</p><div class="grid three"><article class="card newsAccent"><h3>Audiência regional</h3><p>Editorias, manchetes, conteúdos locais e distribuição organizada para manter o público informado e recorrente.</p></article><article class="card newsAccent"><h3>Produtividade editorial</h3><p>RSS, captura automática, categorias e IA editorial como apoio à preparação, organização e enriquecimento de conteúdo.</p></article><article class="card newsAccent"><h3>Receita digital</h3><p>Banners, parceiros, newsletter e recursos comerciais para estruturar monetização além das redes sociais.</p></article></div></section>

<section class="section alt"><span class="eyebrow dark">Módulos disponíveis</span><h2>Uma base enxuta que pode crescer conforme o veículo.</h2><div class="pillGrid"><span>Portal de Notícias</span><span>RSS / Captura Automática</span><span>IA Editorial</span><span>Categorias e Editorias</span><span>Banners e Monetização</span><span>Newsletter</span></div></section>

<section class="section"><span class="eyebrow dark">Planos</span><h2>Escolha a estrutura adequada à sua rotina editorial.</h2><p class="lead">Os planos organizam o acesso aos módulos e a evolução da operação. Integrações, migração de conteúdo e necessidades específicas são definidas na proposta.</p><div class="grid three"><article class="card"><h3>Start</h3><h2>R$ 497/mês</h2><p>Para começar com portal próprio, organização editorial e base profissional de publicação.</p><a class="btn small" href="/solicitacao-institucional.php">Quero o Start</a></article><article class="card newsAccent"><span class="eyebrow dark">Mais indicado</span><h3>Pro</h3><h2>R$ 997/mês</h2><p>Para veículos que precisam ampliar automação, IA editorial, captura de conteúdo e oportunidades de monetização.</p><a class="btn small red" href="/solicitacao-institucional.php">Quero o Pro</a></article><article class="card"><h3>Enterprise</h3><h2>R$ 1.500/mês</h2><p>Para operações de mídia com maior volume, integrações e necessidade de evolução comercial e editorial contínua.</p><a class="btn small" href="/solicitacao-institucional.php">Falar sobre Enterprise</a></article></div></section>

<section class="section alt"><div class="proof"><div><span class="eyebrow dark">Aplicação prática</span><h2>Aprendizado operacional validado na TV Sumaré.</h2><p class="lead">A operação da TV Sumaré contribui para validar rotinas de publicação, organização de notícias, editorias, vídeos e distribuição de conteúdo que também sustentam a evolução do Portal News AI Pro.</p><a class="btn" href="/casos-reais.php">Ver case TV Sumaré</a></div><div class="proofBox"><strong>TV Sumaré</strong><span>notícias • editorias • vídeos • operação digital</span></div></div></section>

<section class="section appCases"><span class="eyebrow dark">Demonstração</span><h2>Visualize um cenário de portal regional.</h2><p class="lead">News 360 permanece como demonstração de referência. Para prova prática, utilize o case real da TV Sumaré.</p><div class="actions"><a class="btn ghost" href="/demos/news-360/">Abrir News 360</a><a class="btn" href="/diagnostico.php">Receber diagnóstico</a></div></section>

<section class="section cta newsCta"><h2>Estruture seu portal para publicar e vender melhor.</h2><p class="lead">Receba uma proposta com plano, módulos e implantação de acordo com a realidade do seu veículo.</p><div class="actions" style="justify-content:center"><a class="btn" href="/solicitacao-institucional.php">Solicitar proposta</a><a class="btn ghost" href="/diagnostico.php">Diagnóstico comercial</a></div></section>
<?php require __DIR__.'/includes/footer.php'; ?>