<?php $title='TV Digital Enterprise'; $description='TV Digital Enterprise da VITRINE IA PRO: portal, vídeos, transmissões, programação, monetização, IA editorial e módulos para operações audiovisuais profissionais.'; require __DIR__.'/includes/header.php'; ?>
<section class="tvSolutionHero refinedHero"><div class="heroGrid"><div><span class="eyebrow">TV Digital Enterprise</span><h1>Seu canal digital com programação, conteúdo, audiência e receita em uma única operação.</h1><p>A TV Digital Enterprise transforma vídeos, notícias, transmissões e conteúdos recorrentes em uma plataforma própria, com identidade da marca, painel editorial, módulos comerciais e evolução por planos.</p><div class="actions"><a class="btn purple" href="/solicitacao-institucional.php">Solicitar proposta</a><a class="btn ghost darkGhost" href="/casos-reais.php">Ver case TV Sumaré</a></div><div class="heroTrust"><span>Portal de notícias</span><span>Vídeos e lives</span><span>PWA/App</span><span>Monetização</span></div></div><div class="playerMini refinedPlayer"><span>▶</span><strong>TV DIGITAL ENTERPRISE</strong><small>notícias • vídeos • programação • ao vivo • monetização</small></div></div></section>

<section class="section"><span class="eyebrow dark">Uma operação completa</span><h2>Mais do que um player de vídeo.</h2><p class="lead">A plataforma integra publicação editorial, audiovisual, distribuição e recursos comerciais para que a operação cresça sem depender de ferramentas desconectadas.</p><div class="grid three"><article class="card tvAccent"><h3>Conteúdo e notícias</h3><p>Portal de notícias, editorias, RSS, captura automática, aprovação editorial e apoio de IA para produtividade.</p></article><article class="card tvAccent"><h3>TV, vídeos e ao vivo</h3><p>Vídeos, TV Play, transmissões, entrevistas, podcasts, programação e organização de acervo multimídia.</p></article><article class="card tvAccent"><h3>Receita e relacionamento</h3><p>Guia comercial, banners, oportunidades locais, newsletter, push e recursos para ampliar audiência e monetização.</p></article></div></section>

<section class="section alt"><span class="eyebrow dark">Módulos disponíveis</span><h2>Comece com o necessário e evolua por módulos.</h2><div class="pillGrid"><span>Portal de Notícias</span><span>RSS / Captura Automática</span><span>Radar Regional</span><span>Aprovação Editorial</span><span>IA Editorial</span><span>Vídeos</span><span>TV Play</span><span>Ao Vivo</span><span>Repórter IA / HeyGen</span><span>Guia Comercial</span><span>Banners e Monetização</span><span>Empregos & Negócios</span><span>Newsletter</span><span>Notificações Push</span><span>PWA / App Android</span><span>Dashboard Editorial</span></div></section>

<section class="section"><span class="eyebrow dark">Planos</span><h2>Estrutura comercial simples para começar e crescer.</h2><p class="lead">Os planos definem a base de recursos e podem receber módulos adicionais conforme a operação. Implantação, integrações e escopo final são confirmados na proposta.</p><div class="grid three"><article class="card"><h3>Start</h3><h2>R$ 497/mês</h2><p>Para operações que precisam colocar portal, conteúdo e presença digital própria em funcionamento com estrutura profissional.</p><a class="btn small" href="/solicitacao-institucional.php">Quero o Start</a></article><article class="card tvAccent"><span class="eyebrow dark">Mais indicado</span><h3>Pro</h3><h2>R$ 997/mês</h2><p>Para operações com rotina editorial mais intensa, automações, recursos multimídia e expansão de audiência e monetização.</p><a class="btn small purple" href="/solicitacao-institucional.php">Quero o Pro</a></article><article class="card"><h3>Enterprise</h3><h2>R$ 1.500/mês</h2><p>Para operações completas que exigem TV Play, ao vivo, dashboard avançado e módulos premium integrados.</p><a class="btn small" href="/solicitacao-institucional.php">Falar sobre Enterprise</a></article></div><p class="note" style="margin-top:18px">Projetos White Label e implantações especiais são avaliados conforme escopo.</p></section>

<section class="section alt"><div class="proof"><div><span class="eyebrow dark">Case real</span><h2>TV Sumaré: tecnologia em operação.</h2><p class="lead">A experiência operacional da TV Sumaré ajuda a validar fluxos reais de notícias, vídeos, organização editorial, distribuição de conteúdo e evolução dos módulos da TV Digital Enterprise.</p><div class="securityList"><span>Rotina editorial</span><span>Notícias e editorias</span><span>Vídeos e multimídia</span><span>Distribuição de conteúdo</span></div><a class="btn" href="/casos-reais.php">Conhecer o case</a></div><div class="proofBox"><strong>TV Sumaré</strong><span>case real • operação editorial • vídeos • notícias</span></div></div></section>

<section class="section appCases"><span class="eyebrow dark">Demonstração</span><h2>Quer visualizar um cenário antes da conversa comercial?</h2><p class="lead">A TV 360 é uma demonstração de referência. O case TV Sumaré mostra uma operação real.</p><div class="actions"><a class="btn ghost" href="/demos/tv-360/">Abrir TV 360</a><a class="btn" href="/diagnostico.php">Receber diagnóstico</a></div></section>

<section class="section cta tvCta"><h2>Coloque sua TV Digital em operação.</h2><p class="lead">Conte o perfil do canal, a estrutura atual e o objetivo comercial. A proposta indica plano, módulos, implantação e próximos passos.</p><div class="actions" style="justify-content:center"><a class="btn" href="/solicitacao-institucional.php">Solicitar proposta</a><a class="btn ghost" href="/diagnostico.php">Diagnóstico comercial</a></div></section>
<?php require __DIR__.'/includes/footer.php'; ?>