<?php

return [
 ['name'=>'Factory','slug'=>'factory','category'=>'Operacao','description'=>'Construcao, gestao e supervisao tecnica dos sistemas.','version'=>'Enterprise 10','branch'=>'feature/factory-enterprise-10-ui','stage'=>'hml','status'=>'active','health'=>'online','integration'=>'sso_active','admin_url'=>'https://factory.hml.vitrineiapro.com.br/admin','roles'=>['admin'],'sso'=>true],
 ['name'=>'Marketing IA','slug'=>'marketing-ia','category'=>'Inteligencia / Automacao','description'=>'Operacao de marketing, campanhas e producao assistida por IA.','version'=>'v1','branch'=>'feature/veo-3-1-video-producer','stage'=>'hml','status'=>'active','health'=>'online','integration'=>'sso_active','admin_url'=>'https://marketing.hml.vitrineiapro.com.br/admin/marketing-dashboard','sso_url'=>'https://marketing.hml.vitrineiapro.com.br/sso/cockpit','sso_target'=>'marketing-ia','roles'=>['admin'],'sso'=>true],
 ['name'=>'Vitrine Social Midia','slug'=>'vitrine-social-midia','category'=>'Produtos','description'=>'Gestao de conteudo, campanhas e operacao de redes sociais.','version'=>'Enterprise','branch'=>'recovery/social-hml-rebuild-20260909','stage'=>'hml','status'=>'active','health'=>'online','integration'=>'direct_admin','admin_url'=>'https://social.hml.vitrineiapro.com.br/admin','roles'=>['admin'],'sso'=>false],
 ['name'=>'Centro Operacional','slug'=>'centro-operacional','category'=>'Operacao','description'=>'Operacao, diagnostico e supervisao da plataforma.','version'=>'V5','branch'=>'backup/v5-pre-production-publication-20260904','stage'=>'hml','status'=>'active','health'=>'online','integration'=>'pending','admin_url'=>null,'roles'=>['admin'],'sso'=>false],
 ['name'=>'Guia Digital da Cidade','slug'=>'guia-digital','category'=>'Produtos','description'=>'Administracao do Guia Digital da Cidade.','version'=>'v1','branch'=>'hml/independent-v1-ready','stage'=>'hml','status'=>'active','health'=>'healthy','integration'=>'pending','admin_url'=>null,'roles'=>['admin'],'sso'=>false],
 ['name'=>'TV Digital Enterprise','slug'=>'tv-digital-enterprise','category'=>'Produtos','description'=>'Administracao da plataforma TV Digital Enterprise.','version'=>'Enterprise','branch'=>'feature/tvsumare-boletim-social','stage'=>'hml','status'=>'active','health'=>'unknown','integration'=>'pending','admin_url'=>null,'roles'=>['admin'],'sso'=>false],
 ['name'=>'AssessorGov IA','slug'=>'assessorgov-ia','category'=>'Produtos','description'=>'Captacao de recursos e apoio operacional para gestao publica.','version'=>'Em desenvolvimento','branch'=>null,'stage'=>'development','status'=>'development','health'=>'not_applicable','integration'=>'pending','admin_url'=>null,'roles'=>['admin'],'sso'=>false],
 ['name'=>'SISMED','slug'=>'sismed','category'=>'Produtos','description'=>'Vertical de Saude Digital Inteligente.','version'=>'Roadmap estrategico','branch'=>null,'stage'=>'development','status'=>'development','health'=>'not_applicable','integration'=>'pending','admin_url'=>null,'roles'=>['admin'],'sso'=>false],
 ['name'=>'Gestao de Cadastros e Atendimentos','slug'=>'gestao-cadastros-atendimentos','category'=>'Projetos','description'=>'Gestao operacional de cadastros, atendimentos, cursos, turmas, inscricoes e filas de espera.','version'=>'0.3.3','branch'=>'main','stage'=>'hml','status'=>'active','health'=>'healthy','integration'=>'direct_admin','admin_url'=>'https://gerocadastro.hml.vitrineiapro.com.br','roles'=>['admin'],'sso'=>false],
];